name: Build and Push Docker Image
  curl -sfL https://get.k3s.io | sh -
  sudo k3s server --disable traefik

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/hermann93360/manycarapp:latest
  RELEASE_NAME: manycar-app
  CHART_DIR: .helm-chart/angular-app

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker Image
        run: |
          docker build . -t ghcr.io/hermann93360/manycarapp:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/hermann93360/manycarapp:latest
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.3'

      - name: Configure kubeconfig
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig


      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_DIR }} \
            --create-namespace \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set image.tag=latest
